name: Docker Image CI

on:
  push:
    branches:
      - docker

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kevin.carrogan.com:$(date +%s)
